### PR TITLE
Add "Move Template" button on lookups

### PR DESCRIPTION
**Pull request by haykam821**
This allows for managing template positions on mobile without having to use a keyboard or edit the URL parameters.

Example of Move Template button

### CODE REVIEW

**Comment by Sorunome** [comment]
maybe chang e the button name to something like "move template here"? i found that labeling a bit confusing at first.

is it possible to hide the button if no template is loaded?

**Comment by haykam821** [comment]
Both of your issues have been addressed.

New preview of Move Template Here button

**Comment by gunnerwolf** [comment]
Is it possible to make the button fit between the other 2 with the longer text if the button styles (padding and margin) are tweaked slightly? Would look a lot cleaner.

**Comment by haykam821** [comment]
Changing the `margin-right` rule on `.button` to `4.5px` solves this issue.

**Comment by gunnerwolf** [comment]
nice one. I won't merge this myself just because I've been inactive on this project for over a year and feel like it's not really my place to merge PRs anymore, so I'll leave that up to @Sorunome, I just wanted to give my $0.02 on the styling of it

**Comment by Sorunome** [comment]
It looks great! I'll merge when on PC, thank you

**Pull request merged**
