### PR TITLE
Add capability to provide extra data for lookup

### PR DESCRIPTION
**Pull request by haykam821**
This pull request changes the system in which lookup data is provided, allowing developers to add their own data to it, along with making the existing data more capable in the future. The developer guide has been updated to demonstrate how this works, and you can use it in a userscript with `App.lookup.registerHook(hook);`

### CODE REVIEW

**Comment by Sorunome** [comment]
What usecase do you see for this?

**Comment by haykam821** [comment]
@Sorunome A few of the main things it can be used for is to let users add custom notes to users, show their Discord tags, and the faction they are aligned with, without having to bake these features into the client itself.

**Comment by Sorunome** [comment]
Sorry, we purposefully cherry-pick which data to display

**Comment by FlyingSixtySix** [comment]
> Sorry, we purposefully cherry-pick which data to display

@Sorunome, what do you mean by this?

**Comment by Sorunome** [comment]
we don't want any additional information to display on user lookup

**Comment by FlyingSixtySix** [comment]
Why restrict users from adding extra client-side information though? This opens up that avenue - while allowing us to keep to our defaults.

**Comment by haykam821** [comment]
A userscript is the user's choice on the client only. No need for main Pxls to support it except for opening up the way to add them more easily.

**Comment by Sorunome** [comment]
Making it easy to display extra stuff like faction would prevent more people from potentially attacking etc. which is already way too little currently.

We discussed this whole thing already for when we discussed if we should add username lookup at all

**Comment by haykam821** [comment]
@Sorunome That faction info is only available via a userscript. If you manage to get that userscript, you're probably in a Discord faction.

**Comment by Sorunome** [comment]
Well, we don't have to support that now

**Comment by haykam821** [comment]
@Sorunome There's an official Discord server where factions are encouraged via the factions channel and diplomat role. Maybe that is what is causing the lack of attacks?

**Comment by Sorunome** [comment]
that is completely different, that is to make it easier to find art others make and join in on it. Now, if a user wants to take a break of that and go over something else....being associated with a faction only hurts.

**Comment by haykam821** [comment]
If a user wants to be associated with the faction... so be it. If they want to have faction info in their lookups... so be it.

**Comment by Sorunome** [comment]
This PR allows others to label other users and have that information very easily accessible, this PR will not be merged.

If you have other feature ideas, maybe ask about them in the issues first before spending time implementing them only for them to not be merged?

**Comment by haykam821** [comment]
How is it very easily accessible? You have to get a userscript to have it show and a whole data set for it to be useful.

**Comment by FlyingSixtySix** [comment]
Keep in mind that this is entirely client-side--what one user does with this has no effect on another user.

**Comment by Sorunome** [comment]
I am.fully aware thjs is client side. Why should we, though, implement an API that goes against some pxls ideas?

**Comment by FlyingSixtySix** [comment]
> that goes against some pxls ideas?
What pxls ideas are we going against?

**Comment by haykam821** [comment]
Which ideas, specifically? I assume you prefer anarchy more than what Place seemed to actually be about:

> There is an empty canvas.
> You may place a tile upon it, but you must wait to place another.
> Individually you can create something.
> Together you can create something more.

**Comment by Doxylamin** [comment]
Sorry for bringing me in now, but my inbox got spammed and I gotta say, i'm with @haykam821 and @FlyingSixtySix on that one.

**Comment by TheRebelG0d** [comment]
This does not go against any "pxls ideals" that I know of... This doesn't return any extra data from the server, so all of the data that could be used by this has already been "cherry picked". All this PR does is allows someone to do the exact same thing as if they were keeping a list of people in notepad and ctrl+f'd every time someone placed a pixel. Some factions already keep a channel dedicated to watching griefers of their project.

I'm with the others on this, I can't really see a reason to block this PR... any chance to reopen and reconsider @Sorunome?

**Comment by haykam821** [comment]
Two of the largest factions have a griefer list in their Discord servers.

* ManePxls: 
ManePxls griefer list
* American Flag in Place: 
AFIP griefer list

These lists have the same amount of accessibility as having it directly provided with a lookup hook.

**Comment by Sorunome** [comment]
@TheRebelG0d i think it is best to move this discussion to our discord

**Comment by haykam821** [comment]
Can we not? I'm banned from the Discord.

**Pull request merged**
