### PR TITLE
Add tendril support

### PR DESCRIPTION
**Pull request by FlyingSixtySix**
This pull request adds support for _tendrils_, or _pixels that may only be placed beside other pixels,_ as a configuration option. This addresses #119.

pxls tendril demo 4

### CODE REVIEW

**Comment by Sorunome** [comment]
nonono the idea was to use the placemap and if the placemap on that index is e.g. 1 we use tendrils - that way we can have mixed canvases!

Am 4. September 2018 03:37:10 MESZ schrieb Andrew Black <notifications@github.com>:

**Comment by FlyingSixtySix** [comment]
> if the placemap on that index is e.g. 1 we use tendrils
I don't understand. How can it be mixed? From what I see - either the entire canvas is tendril-only, tendril around an area only, or not. Also, what do you mean by _that index?_ Index of the pixel the user wants to place at?

**Comment by Sorunome** [comment]
```
if (App.getHavePlacemap()) {
                    canPlace = c != cp.getColor() && App.getPlacemap(cp.getX(), cp.getY()) == 0;
                } else {
                    canPlace = c != cp.getColor() && c != 0xFF && c != -1;
                }
```

if App.getPlacemap(x, y) == 2 you do tendril expansion
that way we have 0 - normal place, 1 - no place, 2 - tendrils

Am 4. September 2018 07:32:49 MESZ schrieb Andrew Black <notifications@github.com>:

**Comment by FlyingSixtySix** [comment]
`if (App.getConfig().getBoolean("tendrils") && App.getPlacemap(cp.getX(), cp.getY()) == 2) {`
So something like this instead?

**Comment by Sorunome** [comment]
the config setting `tendrils` is obsolete with that.

Try storing the result if App.getPlacemap in a variable and do a switch for what to do on what behaviour type

Am 4. September 2018 07:47:24 MESZ schrieb Andrew Black <notifications@github.com>:

**Comment by FlyingSixtySix** [comment]
Is what's in the latest commit what you were speaking off?

**Comment by Sorunome** [comment]
yes exactly! if that works, that is xP

Am 4. September 2018 08:04:16 MESZ schrieb Andrew Black <notifications@github.com>:

**Comment by FlyingSixtySix** [comment]
I'll do some testing in the morning. 👍

**Comment by FlyingSixtySix** [comment]
I don't think this will work - `public static int App.getPlacemap(int x, int y)` returns a 0 or 1, based on the alpha value (cast to int).

**Comment by Sorunome** [comment]
nope it can be anything from 0 - 255 https://github.com/xSke/Pxls/blob/master/src/main/java/space/pxls/App.java#L318-L320

**Pull request merged**
